'use strict';
const $=id=>document.getElementById(id);
const SESSION='anker-session-v2',LEGACY='anker-session-v1',PLAN='anker-plan-v1';
let storageOK=true,clock,messageLevel=0;
function read(key,local=false){try{return JSON.parse((local?localStorage:sessionStorage).getItem(key)||'null')}catch{storageOK=false;return null}}
function remove(key,local=false){try{(local?localStorage:sessionStorage).removeItem(key);return true}catch{storageOK=false;return false}}
function save(){try{sessionStorage.setItem(SESSION,JSON.stringify(s))}catch{storageOK=false}}
function esc(v){return String(v||'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
const emptyPlan=()=>({person:'',phone:'',place:'',emergencyAction:'raum',promise:'',afterwards:'',why:'',review:''});
let plan={...emptyPlan(),...(read(PLAN,true)||{})};
const fields=['person','phone','place','promise','afterwards','why','review'];
fields.forEach(k=>plan[k]=typeof plan[k]==='string'?plan[k]:'');
const fresh=()=>({screen:'home',mode:'normal',urge:5,after:5,thought:'',need:'',action:'',duration:5,deadline:0,closed:false,commit:false,acted:false,contacted:false,prayer:{longing:'',fear:'',help:''},content:{}});
let migrated=false;
let s=read(SESSION);
if(!s){const old=read(LEGACY);s=fresh();if(old&&Number.isInteger(old.step)&&old.step>=0&&old.step<=4){s={...s,...old,screen:['home','close','action','pause','check'][old.step],need:({einsam:'nähe',stress:'ruhe',leer:'reiz',müde:'ruhe',flucht:'flucht',reiz:'reiz'})[old.trigger]||'ruhe'};migrated=true}}
const screens=['home','close','ground','surrender','anchor','thought','need','action','support','pause','check','done','lapse-close','lapse-grace','night-close','night-light','night-pray','night-place'];
if(!s||!screens.includes(s.screen))s=fresh();
s={...fresh(),...s,prayer:{...fresh().prayer,...(s.prayer||{})}};
if(!s.content||typeof s.content!=='object'||Array.isArray(s.content))s.content={};
if(!['normal','urgent','lapse','night'].includes(s.mode))s.mode='normal';
if(![3,5,10].includes(s.duration))s.duration=5;
for(const k of ['urge','after'])if(!Number.isFinite(s[k])||s[k]<0||s[k]>10)s[k]=5;
if(!Number.isFinite(s.deadline))s.deadline=0;
let night=read('anker-night',true);if(typeof night!=='boolean')night=new Date().getHours()>=22||new Date().getHours()<6;
const steps=['Ankommen','Abstand schaffen','Hilfe annehmen','Innehalten','Weitergehen'];
const actionLabels={kontakt:'Einen Menschen kontaktieren',hände:'Zehn Minuten häkeln oder etwas mit den Händen tun',bewegung:'Zehn Minuten langsam gehen',raum:'Raum wechseln und eine kleine Aufgabe machen',ruhe:'Das Handy ablegen und zur Ruhe kommen',papier:'Gedanken auf Papier abladen',raus:'An einen sicheren Ort mit Menschen gehen'};
if(!actionLabels[plan.emergencyAction])plan.emergencyAction='raum';
if(s.action&&!actionLabels[s.action])s.action='';
const needs={
 'nähe':{label:'Nähe',text:'Du darfst Verbindung suchen. Ein vertrauter Mensch kann dich gerade begleiten.',prayer:'Jesus, ich sehne mich nach Nähe. Lass mich bei dir ankommen und hilf mir, mich einem Menschen zuzuwenden.',actions:['kontakt','raus'],verse:2},
 'bestätigung':{label:'Bestätigung',text:'Du darfst mit deinem Wunsch, gesehen zu werden, zu Gott kommen.',prayer:'Vater, ich möchte gesehen werden. Hilf mir, meinen Wert in deiner Liebe zu suchen und ehrlich um Zuspruch zu bitten.',actions:['kontakt','papier'],verse:0},
 'trost':{label:'Trost',text:'Was weh tut, darf ausgesprochen werden. Du musst es nicht verstecken.',prayer:'Jesus, das tut gerade weh. Ich bringe es dir. Hilf mir, Trost und Begleitung anzunehmen.',actions:['kontakt','papier'],verse:3},
 'reiz':{label:'Aufregung',text:'Gib deiner Energie eine kleine Aufgabe mit einem klaren Ende.',prayer:'Gott, ich suche gerade etwas, das mich mitreißt. Hilf mir, eine gute kleine Handlung für jetzt zu wählen.',actions:['hände','bewegung'],verse:4},
 'flucht':{label:'Flucht',text:'Für jetzt reicht es, das Gefühl zu benennen und einen überschaubaren Schritt zu gehen.',prayer:'Jesus, ich möchte gerade vor etwas weglaufen. Ich lege dir meine Angst hin. Hilf mir beim nächsten kleinen Schritt.',actions:['papier','kontakt'],verse:3},
 'ruhe':{label:'Ruhe',text:'Du darfst müde sein. Fürsorge kann jetzt eine Pause und ein abgelegtes Handy bedeuten.',prayer:'Vater, ich bin erschöpft. Hilf mir, Ruhe anzunehmen und mich nicht mit weiterem Input wachzuhalten.',actions:['ruhe','raum'],verse:1}
};
const thoughts={five:['„Nur fünf Minuten.“','Du musst die fünf Minuten jetzt nicht ausdiskutieren. Verschiebe die Entscheidung und lege das Handy ab.'],look:['„Nur kurz nachsehen.“','Nachsehen kann der Einstieg werden. Lass den Chat geschlossen und gib dir zuerst Abstand.'],lost:['„Heute ist sowieso alles egal.“','Du darfst mitten im Tag neu anfangen. Auch jetzt zählt eine Unterbrechung.'],deserve:['„Das habe ich mir verdient.“','Du darfst dir etwas Gutes tun. Wähle etwas, das dir auch danach guttut.'],other:['Keiner davon / ich weiß es nicht','Du musst den Gedanken nicht vollständig verstehen, um jetzt eine Pause zu machen.']};
const actionText={kontakt:['Sprich eine vertraute Person an oder ruf sie an.','Bitte sie, kurz bei dir zu bleiben, mit dir zu beten oder mit dir zu gehen.'],hände:['Nimm dein Häkelzeug oder eine kleine Aufgabe für deine Hände.','Bleib zehn Minuten bei dieser einen Sache.'],bewegung:['Geh langsam durch die Wohnung oder eine sichere kurze Runde draußen.','Spüre deine Schritte und lass die Schultern locker.'],raum:['Wechsle in einen anderen Raum.','Räume eine kleine Fläche auf oder kümmere dich um eine einfache Alltagsaufgabe.'],ruhe:['Mach es dir ruhig. Du musst jetzt nichts leisten.','Erlaube dir, auszuruhen oder zu schlafen.'],papier:['Nimm Papier und Stift.','Schreib: „Ich fühle … und brauche gerade …“.'],raus:['Geh an einen sicheren, erreichbaren Ort mit Menschen.','Nimm deine Umgebung wahr und suche bei Bedarf Kontakt.']};
const messages=['Hast du kurz Zeit?','Ich brauche gerade Unterstützung. Kannst du kurz bei mir bleiben?','Ich habe gerade Suchtdruck. Kannst du kurz bei mir bleiben, mit mir beten oder mit mir rausgehen?'];
const commitment='Gott hilft mir. Ich gehe den nächsten Schritt.';
function commitmentValid(v){return [commitment,'Ich muss dem Impuls nicht folgen.'].some(t=>t.toLocaleLowerCase('de').replace(/[.!]+$/,'')===String(v).trim().toLocaleLowerCase('de').replace(/[.!]+$/,''))}
function place(){return plan.place||'an einen festen Platz außer Reichweite'}
function remaining(){return Math.max(0,Math.ceil((s.deadline-Date.now())/1000))}
function hasCard(){return !!(plan.promise||plan.afterwards||plan.why)}
function selectedNeed(){return needs[s.need]||needs.ruhe}
function preparedAction(){return actionLabels[plan.emergencyAction]?plan.emergencyAction:'raum'}
function go(screen){s.screen=screen;save();render(true)}
function start(mode){const urge=s.urge;s=fresh();s.mode=mode;s.urge=mode==='urgent'||mode==='lapse'?9:urge;s.duration=mode==='normal'?5:3;if(mode==='night'){night=true;applyNight();go('night-close')}else go(mode==='lapse'?'lapse-close':'close')}
function startPause(){if(!s.action)s.action=preparedAction();s.deadline=Date.now()+s.duration*60000;s.acted=false;go('pause')}
function finish(){s.screen='done';s.prayer=fresh().prayer;remove(SESSION);remove(LEGACY);render(true)}
function group(){if(s.screen==='home')return 0;if(['close','ground','surrender','lapse-close','lapse-grace','night-close','night-light','night-pray'].includes(s.screen))return 1;if(['anchor','thought','need','action','support','night-place'].includes(s.screen))return 2;if(s.screen==='pause')return 3;return 4}
function heading(title,lead=''){return `<div class="stephead"><span class="step-title">${s.mode==='urgent'?'Sofort-Hilfe':s.mode==='lapse'?'Jetzt neu anfangen':s.mode==='night'?'Zur Ruhe kommen':steps[group()]}</span><span class="step-count">${String(group()+1).padStart(2,'0')} <span>/ 05</span></span></div><h1>${title}</h1>${lead?`<p class="lead">${lead}</p>`:''}`}
function btn(id,label,disabled=false,kind='primary'){return `<button id="${id}" class="${kind} wide" ${disabled?'disabled':''}>${label}</button>`}
function verse(i){const id=pickContent('verse-'+i,versePools[i].map(n=>'verse-'+n));const v=verses[Number(id.slice(6))];return `<section class="verse" aria-label="Biblische Zusage"><div class="verse-top"><span>Gottes Zusage</span><a href="https://www.die-bibel.de/bibel/LU12/${v.url}" target="_blank" rel="noopener">${v.ref}</a></div><p class="verse-text">„${v.text}“</p><details><summary>Für diesen Moment</summary><p class="hint">${v.note}</p><span class="small">Lutherbibel 1912 · Auszug. Die Anwendung ist ein geistlicher Impuls.</span></details>${feedback(id)}</section>`}
function score(id,label,value){return `<div class="range-head"><label for="${id}" style="margin:0">${label}</label><output class="score" id="${id}Value" for="${id}">${value}<span class="small"> / 10</span></output></div><input type="range" id="${id}" min="0" max="10" step="1" value="${value}"><div class="range-ends"><span>Kein Drang</span><span>Sehr stark</span></div>`}
function card(){return `<div class="personal-card"><span class="eyebrow">VON DEINEM KLAREN ICH</span>${[['Was mich lockt',plan.promise],['Wie es mir danach geht',plan.afterwards],['Wofür ich frei werden möchte',plan.why]].filter(x=>x[1]).map(([title,text])=>`<h3>${title}</h3><p>${esc(text)}</p>`).join('')}</div>`}
function prayerForm(){return `<details><summary>Mein Gebet mit eigenen Worten</summary><p class="small">Ergänze die Sätze still oder schreibe sie hier auf. Schreiben ist freiwillig.</p>${[['longing','Jesus, gerade sehne ich mich nach …'],['fear','Ich habe Angst, dass …'],['help','Hilf mir jetzt bei …']].map(([k,label])=>`<label>${label}<textarea id="prayer-${k}" class="prayer-input" data-key="${k}" maxlength="240" rows="2">${esc(s.prayer[k])}</textarea></label>`).join('')}<p class="small">Geschriebene Gebetssätze werden nach Abschluss dieser Pause entfernt.</p></details>`}
function timer(){return `<div class="timer" id="timer"><strong id="countdown" aria-label="Verbleibende Wartezeit"></strong><span id="timerCaption">Zeit für Abstand</span></div><p id="timerStatus" role="status"></p>`}
function support(){return `${heading('Lass deine Last mittragen.','Dein vorbereiteter Plan nimmt dir jetzt eine Entscheidung ab.')}${verse(2)}<div class="callout"><strong>${plan.person?esc(plan.person)+' um Begleitung bitten':'Einen vertrauten Menschen dazuholen'}</strong><p>Bitte die Person, kurz bei dir zu bleiben oder mit dir zu beten.</p></div>${btn('contactNow','Kontakt & Nachricht öffnen',false,'secondary')}${btn('reached','Ich habe jemanden erreicht')}${btn('unreachable','Niemand erreichbar – nächster Schritt',false,'secondary')}${s.mode==='lapse'?'<p class="small quiet">Später kannst du unter „Mein Plan · Später zurückblicken“ festhalten, welche Hürde dir helfen würde.</p>':''}`}
function render(focus=false){clearInterval(clock);applyNight();document.body.classList.toggle('complete',s.screen==='done');$('journey').innerHTML=steps.map((name,i)=>`<li class="${i===group()?'active':i<group()?'done':''}" ${i===group()?'aria-current="step"':''}><span class="num">${i<group()?'✓':i+1}</span><span class="stepname">${name}</span></li>`).join('');let h='';
if(s.screen==='home')h=`${heading('Du musst das nicht allein schaffen.','Mit Gott innehalten. Hilfe annehmen. Einen Schritt gehen.')}${btn('urgent','Ich bin kurz davor')}<p class="small center">Sofort starten · eine Aufgabe pro Bildschirm</p><div class="input-section">${score('urge','Wie stark ist der Drang?',s.urge)}<div id="highPlan"></div>${btn('normal','Geführte Pause starten',false,'secondary')}</div><div class="entry-links">${btn('lapse','Ich habe wieder angefangen',false,'secondary')}${btn('nightStart','Ich möchte zur Ruhe kommen',false,'secondary')}</div>${verse(0)}`;
if(s.screen==='close')h=s.mode==='urgent'?`${heading('Schließe jetzt den Chat.','Komm danach für den nächsten kleinen Schritt hierher zurück.')}<div class="single-task">Du musst nur diese eine Handlung tun.</div>${btn('closedQuick','Der Chat ist geschlossen')}`:`${heading('Schaffe Abstand.','Schließe den auslösenden Chat. Du darfst Gott dabei um Hilfe bitten.')}${verse(1)}${plan.review?`<div class="callout"><strong>Deine vereinbarte Hürde</strong><p>${esc(plan.review)}</p></div>`:''}<label class="check"><input id="closed" type="checkbox" ${s.closed?'checked':''}> Der Chat ist geschlossen.</label><label for="commit">Schreib deinen Entschluss einmal auf:</label><div class="commit-sentence">${commitment}</div><input id="commit" placeholder="${commitment}" value="${s.commit?commitment:''}" autocomplete="off"><details><summary>Alternative zum Tippen</summary><label class="check"><input id="accessible" type="checkbox" ${s.commit?'checked':''}> Ich habe den Satz bewusst gelesen oder gesagt.</label></details><h3>Deine Pause</h3><div class="duration">${[3,5,10].map(n=>`<button class="choice duration-choice" data-value="${n}" aria-pressed="${s.duration===n}">${n} Minuten</button>`).join('')}</div>${btn('closeNext','Mit Gottes Hilfe weiter',!s.closed||!s.commit)}`;
if(s.screen==='ground')h=`${heading('Spüre deine Füße.','Stell beide Füße auf den Boden oder spüre, wo dein Körper aufliegt.')}<div class="single-task">Nimm den Kontakt zur Unterlage wahr.<br>Atme so, wie es angenehm ist.</div>${btn('groundNext','Weiter')}`;
if(s.screen==='surrender')h=`${heading('Bitte Gott um Hilfe.','Du brauchst keine perfekten Worte.')}<div class="prayer large-prayer">Jesus, ich schaffe es gerade nicht allein. Sei mir nah und hilf mir beim nächsten Schritt. Amen.</div><p class="small">Du darfst auch einfach still vor Gott sein.</p>${btn('surrenderNext','Weiter mit Gottes Hilfe')}`;
if(s.screen==='anchor')h=`${heading('Deine eigenen Worte.','Du hast sie in einem ruhigeren Moment für dich festgehalten.')}${card()}${btn('anchorNext','Daran möchte ich mich orientieren')}`;
if(s.screen==='thought')h=`${heading('Welcher Gedanke lockt dich?','Erkennen reicht. Du musst ihn nicht ausdiskutieren.')}<div class="choices action-choices">${Object.entries(thoughts).map(([k,v])=>`<button class="choice thought-choice" data-value="${k}" aria-pressed="${s.thought===k}">${v[0]}</button>`).join('')}</div>${s.thought?`<div class="callout" role="status">${thoughts[s.thought]?.[1]||''}</div>`:''}${btn('thoughtNext','Die Entscheidung jetzt verschieben',!s.thought)}`;
if(s.screen==='need')h=`${heading('Was suchst du gerade?','Dein Bedürfnis darf da sein. Wähle, was am ehesten passt.')}<div class="choices">${Object.entries(needs).map(([k,n])=>`<button class="choice need-choice" data-value="${k}" aria-pressed="${s.need===k}">${n.label}</button>`).join('')}</div>${s.need?`<div class="callout">${selectedNeed().text}</div>`:''}${btn('needNext','Einen passenden Schritt wählen',!s.need)}`;
if(s.screen==='action'){const n=selectedNeed(),list=[...new Set([...n.actions,'kontakt'])];h=`${heading('Gib deinem Bedürfnis Raum.',n.text)}${verse(n.verse)}${prayerBlock()}<h3>Was tust du während der Pause?</h3>${actionBlock(list)}${prayerForm()}${btn('pauseStart','Pause starten & diesen Schritt gehen',!s.action)}`}
if(s.screen==='support')h=support();
if(s.screen==='lapse-close')h=`${heading('Du kannst jetzt unterbrechen.','Auch wenn du schon angefangen hast: Schließe den Chat jetzt.')}<div class="single-task">Eine Unterbrechung ist auch mittendrin möglich.</div>${btn('lapseClosed','Ich habe den Chat geschlossen')}`;
if(s.screen==='lapse-grace')h=`${heading('Komm wieder zu Gott.','Du musst dich nicht verstecken. Du darfst neu anfangen und Hilfe annehmen.')}${verse(5)}<div class="prayer large-prayer">Jesus, hier bin ich. Ich bringe dir, was passiert ist. Hilf mir, jetzt zu dir umzukehren und Unterstützung anzunehmen. Amen.</div>${btn('lapseHelp','Jetzt Unterstützung organisieren')}`;
if(s.screen==='night-close')h=`${heading('Für heute darf es ruhig werden.','Schließe den auslösenden Chat.')}<div class="single-task">Du musst heute nichts mehr mit dem Chat klären.</div>${btn('nightClosed','Der Chat ist geschlossen')}`;
if(s.screen==='night-light')h=`${heading('Mach das Licht angenehm.','Wenn es gerade möglich ist: Dämpfe dein Raumlicht oder die Bildschirmhelligkeit von Hand.')}<p class="small">Die App ändert nur ihre eigene Darstellung.</p>${btn('nightLight','Weiter')}`;
if(s.screen==='night-pray')h=`${heading('Lege den Tag in Gottes Hände.')}<div class="prayer large-prayer">Vater, ich gebe dir diesen Tag und das, was mich noch zieht. Hilf mir, für heute loszulassen und zu ruhen. Amen.</div>${btn('nightPray','Jetzt das Handy ablegen')}`;
if(s.screen==='night-place')h=`${heading('Dein Handy bekommt einen Ruheplatz.')}<div class="single-task">Lege es ${esc(place())}.</div><p class="lead">Starte die kurze Pause und lege es dann ab. Du musst nicht auf den Bildschirm schauen.</p>${btn('nightPause','Drei Minuten Ruhe starten')}`;
if(s.screen==='pause'){const simple=s.mode!=='normal';h=`${heading(s.mode==='night'?'Du darfst jetzt ruhen.':'Gott trägt dich durch diesen Moment.',simple?'Du kannst das Handy jetzt ablegen.':'Du darfst den Drang wahrnehmen und trotzdem deinen Schritt gehen.')}${timer()}<div class="offline-task"><span class="eyebrow">JETZT IM ALLTAG</span><h2>${esc(actionLabels[s.action]||actionLabels.raum)}</h2><p>Handy ${esc(place())}.</p>${!simple?`<ul class="tasklist">${(actionText[s.action]||actionText.raum).map((t,i)=>`<li><span>${i+1}</span>${t}</li>`).join('')}</ul>`:''}</div>${s.action==='kontakt'?btn('contactNow','Kontakt & Nachricht öffnen',false,'secondary'):''}${!simple?`${verse(3)}<details><summary>Ein Gebet für die Pause</summary><p>${chosenPrayer().text}</p></details>`:'<p class="prayer-line">Gott, hilf mir, diesen Moment mit dir zu gehen.</p>'}<p class="small">Die Zeit läuft bei gesperrtem Handy und nach Neuladen weiter.</p>${btn('pauseNext',s.mode==='night'?'Zur Ruhe kommen':'Nach der Pause neu einschätzen',true)}`}
if(s.screen==='check')h=`${heading('Wie ist es jetzt?','Der Drang muss nicht verschwunden sein. Du darfst weiter Hilfe annehmen.')}<div class="input-section">${score('after','Dein Drang nach der Pause',s.after)}<label class="check"><input id="acted" type="checkbox" ${s.acted?'checked':''}> Ich habe meinen Schritt außerhalb des Bildschirms gemacht.</label></div><div id="assessment"></div>${btn('finish','Jetzt vom Bildschirm lösen',!s.acted)}${btn('repeat','Noch eine Pause einlegen',false,'secondary')}`;
if(s.screen==='done')h=`<span class="eyebrow">DEIN NÄCHSTER SCHRITT</span><h1 class="finish-title">${s.mode==='night'?'Handy ablegen.<br>Zur Ruhe kommen.':s.after>=7&&!s.contacted?'Einen Menschen dazuholen.':esc(actionLabels[s.action]||actionLabels.raum)+'.'}</h1><p class="finish-place">Handy ${esc(place())}.</p>${s.mode!=='night'?'<p class="lead">Bleib die nächsten zehn Minuten bei diesem Schritt.</p>':''}<p class="prayer-line">Gott, begleite mich. Hilf mir, deinen nächsten Schritt zu gehen. Amen.</p><p class="small">Du kannst die App jetzt schließen.</p><button class="minor" id="restart">Eine neue Notfall-Pause starten</button>`;
if(s.screen!=='done')h+='<button class="minor resistance-link" id="resistOpen">Ich will die Hilfe gerade umgehen</button>';
$('main').innerHTML=h;bind();bindFeedback();if(s.screen==='home')updateHighPlan();if(s.screen==='check')assessment();if(s.screen==='pause'){tick();if(remaining()>0)clock=setInterval(tick,500)}if(focus){$('main').focus();if(window.innerWidth<801)$('main').scrollIntoView({block:'start',behavior:'instant'})}}
function on(id,fn){if($(id))$(id).onclick=fn}
function bind(){on('resistOpen',openResistance);on('urgent',()=>start('urgent'));on('normal',()=>start('normal'));on('lapse',()=>start('lapse'));on('nightStart',()=>start('night'));
 on('closedQuick',()=>{s.closed=true;go('ground')});on('groundNext',()=>go('surrender'));on('surrenderNext',()=>go(hasCard()?'anchor':'support'));on('anchorNext',()=>go(s.mode==='urgent'||s.urge>=7?'support':'need'));
 on('closeNext',()=>{if(s.closed&&s.commit)go(s.urge>=7?(hasCard()?'anchor':'support'):'thought')});on('thoughtNext',()=>{if(s.thought)go(hasCard()?'anchor':'need')});on('needNext',()=>{if(s.need)go('action')});on('pauseStart',()=>{if(s.action)startPause()});
 on('contactNow',openHelp);on('reached',()=>{s.contacted=true;s.action=preparedAction();startPause()});on('unreachable',()=>{s.contacted=false;s.action=preparedAction()==='kontakt'?'raum':preparedAction();startPause()});
 on('lapseClosed',()=>{s.closed=true;go('lapse-grace')});on('lapseHelp',()=>go('support'));on('nightClosed',()=>{s.closed=true;go('night-light')});on('nightLight',()=>go('night-pray'));on('nightPray',()=>go('night-place'));on('nightPause',()=>{s.action='ruhe';s.duration=3;startPause()});
 on('pauseNext',()=>{if(remaining()>0)return;if(s.mode==='night')finish();else{s.after=s.urge;go('check')}});on('finish',()=>{if(s.acted)finish()});on('repeat',()=>{s.urge=s.after;if(s.after>=7)go('support');else startPause()});on('restart',()=>{s=fresh();remove(SESSION);render(true)});
 for(const id of ['urge','after'])if($(id))$(id).oninput=e=>{s[id]=Number(e.target.value);$(id+'Value').innerHTML=s[id]+'<span class="small"> / 10</span>';save();if(id==='urge')updateHighPlan();else assessment()};
 if($('closed'))$('closed').onchange=e=>{s.closed=e.target.checked;updateGate()};
 if($('commit'))$('commit').oninput=e=>{s.commit=commitmentValid(e.target.value)||$('accessible').checked;updateGate()};
 if($('accessible'))$('accessible').onchange=e=>{s.commit=e.target.checked||commitmentValid($('commit').value);updateGate()};
 if($('acted'))$('acted').onchange=e=>{s.acted=e.target.checked;save();$('finish').disabled=!s.acted};
 for(const [selector,key] of [['.thought-choice','thought'],['.need-choice','need'],['.action-choice','action'],['.duration-choice','duration']])document.querySelectorAll(selector).forEach(b=>b.onclick=()=>{s[key]=key==='duration'?Number(b.dataset.value):b.dataset.value;if(key==='need')s.action='';save();render();document.querySelector(`${selector}[data-value="${b.dataset.value}"]`)?.focus()});
 document.querySelectorAll('.prayer-input').forEach(el=>el.oninput=e=>{s.prayer[el.dataset.key]=e.target.value;save()});
}
function updateGate(){save();$('closeNext').disabled=!(s.closed&&s.commit)}
function updateHighPlan(){if(!$('highPlan'))return;$('highPlan').innerHTML=s.urge>=7?`<div class="callout"><strong>Dein Plan für starken Drang</strong><p>${plan.person?esc(plan.person)+' um Begleitung bitten.':'Einen vertrauten Menschen dazuholen.'} Handy ${esc(place())}.</p><p>${esc(actionLabels[preparedAction()])}.</p>${plan.review?`<p><strong>Deine Hürde:</strong> ${esc(plan.review)}</p>`:''}</div>`:''}
function tick(){if(!$('countdown'))return;const t=remaining();$('countdown').textContent=String(Math.floor(t/60)).padStart(2,'0')+':'+String(t%60).padStart(2,'0');$('pauseNext').disabled=t>0;if(t===0){$('timer').classList.add('done');$('timerCaption').textContent='Zeit für den nächsten Schritt';$('timerStatus').textContent='Die Wartephase ist vorbei.';clearInterval(clock)}}
function assessment(){const high=s.after>=7,up=s.after>s.urge;$('assessment').innerHTML=`<div class="callout"><strong>${high?'Hol dir jetzt Begleitung.':up?'Du darfst weiter um Hilfe bitten.':'Dein nächster Schritt zählt.'}</strong><p>${high?'Der Drang ist weiterhin stark. Nutze deinen vorbereiteten Plan und bitte einen Menschen, bei dir zu bleiben.':up?'Ein höherer Wert ist kein Urteil über deinen Glauben. Mehr Abstand und Unterstützung dürfen jetzt dazukommen.':'Bleib bei deiner Handlung und lass den Chat geschlossen. Gott um Hilfe zu bitten und zu handeln gehören zusammen.'}</p></div>${high||up?btn('assessHelp','Einen Menschen kontaktieren',false,'secondary'):''}`;on('assessHelp',openHelp)}
function applyNight(){document.body.classList.toggle('night',!!night);$('nightToggle').setAttribute('aria-pressed',String(!!night));$('nightToggle').textContent=night?'Nachtansicht an':'Nachtansicht'}
function updateMessage(){ $('messageChoices').innerHTML=['Kurz & offen','Unterstützung erbitten','Suchtdruck & Gebet'].map((t,i)=>`<button class="choice message-choice" data-value="${i}" aria-pressed="${messageLevel===i}">${t}</button>`).join('');$('messageText').textContent=messages[messageLevel];document.querySelectorAll('.message-choice').forEach(b=>b.onclick=()=>{messageLevel=Number(b.dataset.value);$('copyStatus').textContent='';updateMessage()})}
function openHelp(){const raw=String(plan.phone||'').replace(/[^+0-9]/g,'');const number=raw.replace(/(?!^)\+/g,'');$('personalContact').innerHTML=number.replace(/\D/g,'').length>=5?`<a class="primary contact-link" href="tel:${esc(number)}">${esc(plan.person||'Vertraute Person')} anrufen</a>`:`<p class="small">${plan.person?esc(plan.person)+' ist dein gewählter Kontakt. ':''}Öffne deine Kontakte oder sprich jemanden direkt an. Du kannst im persönlichen Plan eine Nummer hinterlegen.</p>`;$('copyStatus').textContent='';updateMessage();if(!$('helpDialog').open)$('helpDialog').showModal()}
$('helpOpen').onclick=openHelp;
$('nightToggle').onclick=()=>{night=!night;try{localStorage.setItem('anker-night',JSON.stringify(night))}catch{storageOK=false}applyNight()};
$('planOpen').onclick=()=>{fields.forEach(k=>$(k).value=plan[k]||'');$('emergencyAction').value=preparedAction();$('remember').checked=!!read(PLAN,true);$('planStatus').textContent='';$('prefsResetStatus').textContent='';$('planDialog').showModal()};
$('planForm').onsubmit=e=>{e.preventDefault();fields.forEach(k=>plan[k]=$(k).value.trim());plan.emergencyAction=$('emergencyAction').value;if(!actionLabels[plan.emergencyAction])plan.emergencyAction='raum';if($('remember').checked){try{localStorage.setItem(PLAN,JSON.stringify(plan))}catch{storageOK=false;$('planStatus').textContent='Speichern ist nicht möglich. Deine Änderungen gelten für diese geöffnete Seite. Ein zuvor gespeicherter Plan wurde nicht aktualisiert.';return}}else if(!remove(PLAN,true)){$('planStatus').textContent='Der alte gespeicherte Plan konnte nicht entfernt werden. Die Änderungen gelten nur für diese Seite.';return}$('planDialog').close();render()};
$('deletePlan').onclick=()=>{if(!remove(PLAN,true)){$('planStatus').textContent='Löschen ist nicht möglich. Bitte entferne die Websitedaten in deinem Browser.';return}plan=emptyPlan();fields.forEach(k=>$(k).value='');$('emergencyAction').value='raum';$('remember').checked=false;$('planStatus').textContent='Der gespeicherte Plan und die Erinnerungskarte wurden gelöscht.';render()};
 document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>b.closest('dialog').close());
$('infoOpen').onclick=()=>{$('storageInfo').textContent=storageOK?'Bei einem geteilten Gerät: Nutze ein eigenes Browserprofil. Du kannst deinen gespeicherten Plan unter „Mein Plan“ löschen.':'Browser-Speicher ist nicht verfügbar. Eingaben und Wartephase können beim Neuladen verloren gehen.';$('infoDialog').showModal()};
$('copyMessage').onclick=async()=>{try{await navigator.clipboard.writeText(messages[messageLevel]);$('copyStatus').textContent='Kopiert. Du entscheidest selbst, an wen du den Text sendest.'}catch{$('copyStatus').textContent='Kopieren ist hier nicht möglich. Markiere den Satz oben und kopiere ihn selbst.'}};
try{if(document.modelContext?.registerTool)document.modelContext.registerTool({name:'read_pause_status',description:'Read the current pause stage and remaining wait, without personal entries or changing the flow.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||typeof input!=='object'||Array.isArray(input)||Object.keys(input).length)throw new Error('Expected an empty object');return {step:s.screen==='done'?'finished':steps[group()],remaining_seconds:s.screen==='pause'?remaining():0}}})?.catch?.(()=>{})}catch{}

const verses=[
 {ref:'Hebräer 4,16',text:'Barmherzigkeit empfangen und Gnade finden',url:'HEB.4',note:'Jesus kennt unsere Schwachheit (Vers 15). Darum dürfen wir mit unserem Hilfebedarf zu Gott kommen.'},
 {ref:'2. Korinther 12,9',text:'Laß dir an meiner Gnade genügen; denn meine Kraft ist in den Schwachen mächtig.',url:'2CO.12',note:'Paulus erfährt Gottes Kraft mitten in bleibender Schwäche. Du musst dich für Hilfe nicht erst stark fühlen.'},
 {ref:'Galater 6,2',text:'Einer trage des andern Last',url:'GAL.6',note:'Hilfe anzunehmen passt zum Glauben. Deine Last darf von anderen mitgetragen werden.'},
 {ref:'1. Petrus 5,7',text:'Alle eure Sorge werfet auf ihn; denn er sorget für euch.',url:'1PE.5',note:'Du darfst Gott sagen, was dich zieht und belastet. Er sorgt für dich, auch wenn deine Gefühle noch unruhig sind.'},
 {ref:'Philipper 2,13',text:'Denn Gott ist’s, der in euch wirkt beides, das Wollen und das Vollbringen, nach seinem Wohlgefallen.',url:'PHP.2',note:'Bitte Gott um Hilfe für deinen nächsten konkreten Schritt. Dein Handeln und seine Hilfe gehören zusammen.'},
 {ref:'Römer 8,1',text:'So ist nun nichts Verdammliches an denen, die in Christo Jesu sind',url:'ROM.8',note:'In Christus darfst du aus Gnade neu anfangen. Ein Rückfall ist ein Anlass, Hilfe zu suchen, kein Urteil über deinen Wert.'}
];

const PREFS='anker-content-v1';
const loadedPrefs=read(PREFS,true);
let contentPrefs={ratings:{...(loadedPrefs?.ratings||{})},last:{...(loadedPrefs?.last||{})}};
const versePools=[[0,5,3],[1,0,4],[2,0,3],[3,1,0],[4,1,0],[5,0,1]];
const prayerAlternatives={
 'nähe':'Vater, ich darf Nähe brauchen. Hilf mir, einen echten Menschen anzusprechen und mich von dir halten zu lassen.',
 'bestätigung':'Jesus, du siehst mich. Hilf mir, mich dir ehrlich zu zeigen und freundlichen Zuspruch anzunehmen.',
 'trost':'Vater, ich lege dir hin, was weh tut. Trag mich durch diesen Moment und öffne mir einen Weg zu menschlichem Trost.',
 'reiz':'Jesus, ich bin unruhig und suche einen Reiz. Begleite mich in eine kleine Handlung, die mir guttut.',
 'flucht':'Gott, hier ist das Gefühl, dem ich ausweichen möchte. Hilf mir, es dir zu sagen und nur den nächsten Schritt zu gehen.',
 'ruhe':'Jesus, für jetzt darf es genug sein. Hilf mir, das Handy abzulegen und Ruhe anzunehmen.'
};
function persistPrefs(){try{localStorage.setItem(PREFS,JSON.stringify(contentPrefs));return true}catch{storageOK=false;return false}}
function pickContent(slot,ids){if(ids.includes(s.content[slot]))return s.content[slot];const score=id=>contentPrefs.ratings[id]===1?1:contentPrefs.ratings[id]===-1?-1:0;const best=Math.max(...ids.map(score));const pool=ids.filter(id=>score(id)===best);const old=pool.indexOf(contentPrefs.last[slot]);const selected=pool[(old+1)%pool.length];s.content[slot]=selected;contentPrefs.last[slot]=selected;persistPrefs();if(s.screen!=='done')save();return selected}
function feedback(key){const rating=contentPrefs.ratings[key];return `<details class="feedback-fold"><summary>Diesen Inhalt bewerten</summary><div class="feedback-buttons"><button type="button" class="content-feedback" data-key="${esc(key)}" data-value="1" aria-pressed="${rating===1}">Das hilft mir</button><button type="button" class="content-feedback" data-key="${esc(key)}" data-value="-1" aria-pressed="${rating===-1}">Passt gerade nicht</button></div><p class="small feedback-status" id="feedback-${esc(key)}" role="status"></p></details>`}
function chosenPrayer(){const need=needs[s.need]?s.need:'ruhe';const key=pickContent('prayer-'+need,['prayer-'+need+'-0','prayer-'+need+'-1']);return {key,text:key.endsWith('-0')?needs[need].prayer:prayerAlternatives[need]}}
function prayerBlock(){const p=chosenPrayer();return `<div class="prayer"><span class="eyebrow">DEIN GEBETSIMPULS</span><p>${p.text}</p>${feedback(p.key)}</div>`}
function suggestedAction(list){return pickContent('action-'+(s.need||'ruhe'),list.map(a=>'action-'+a)).slice(7)}
function actionBlock(list){const a=suggestedAction(list);return `<div class="action-suggestion"><span class="eyebrow">EIN VORSCHLAG FÜR JETZT</span><h3>${actionLabels[a]}</h3><button class="choice action-choice" data-value="${a}" aria-pressed="${s.action===a}">${s.action===a?'Diesen Schritt habe ich gewählt':'Diesen Schritt wählen'}</button>${feedback('action-'+a)}</div><details><summary>Eine andere Handlung wählen</summary><div class="choices action-choices">${list.filter(k=>k!==a).map(k=>`<button class="choice action-choice" data-value="${k}" aria-pressed="${s.action===k}">${actionLabels[k]}</button>`).join('')}</div></details>${s.action?`<p class="small selected-action" role="status">Gewählt: ${esc(actionLabels[s.action])}</p>`:''}`}
function validRatingKey(key){return /^verse-[0-5]$/.test(key)||Object.keys(needs).some(n=>key==='prayer-'+n+'-0'||key==='prayer-'+n+'-1')||Object.keys(actionLabels).some(a=>key==='action-'+a)}
function bindFeedback(){document.querySelectorAll('.content-feedback').forEach(b=>b.onclick=()=>{const key=b.dataset.key,value=Number(b.dataset.value);if(!validRatingKey(key)||![1,-1].includes(value))return;if(contentPrefs.ratings[key]===value)delete contentPrefs.ratings[key];else contentPrefs.ratings[key]=value;const saved=persistPrefs();document.querySelectorAll('.content-feedback').forEach(other=>{if(other.dataset.key===key)other.setAttribute('aria-pressed',String(Number(other.dataset.value)===contentPrefs.ratings[key]))});const status=$('feedback-'+key);if(status)status.textContent=saved?(contentPrefs.ratings[key]===1?'Bei künftigen Pausen bevorzugt.':contentPrefs.ratings[key]===-1?'Bei künftigen Pausen nachrangig. Du kannst diesen Inhalt für jetzt beiseitelassen.':'Rückmeldung zurückgenommen.'):'Für diese geöffnete Seite berücksichtigt. Speichern auf dem Gerät ist nicht möglich.'})}
function openResistance(){const own=plan.why||plan.afterwards||plan.promise;$('resistBody').innerHTML=`<p>Du musst dich dafür nicht rechtfertigen. Für jetzt reicht eine Handlung.</p><div class="personal-card"><span class="eyebrow">${own?'DEINE EIGENEN WORTE':'FÜR DIESEN MOMENT'}</span><p>${esc(own||'Du darfst Gott um Hilfe bitten und jetzt eine Unterbrechung schaffen.')}</p></div><div class="single-task">Lege dein Handy ${esc(place())}.</div><p class="prayer-line">Jesus, hilf mir bei genau diesem Schritt.</p><button type="button" id="resistDo" class="primary wide">Ich lege es jetzt ab</button>`;on('resistDo',()=>{$('resistBody').innerHTML=`<div class="single-task">Handy ${esc(place())}.</div><p>Du kannst die App jetzt schließen.</p><p class="small">Deine laufende Pause bleibt erhalten.</p>`});if(!$('resistDialog').open)$('resistDialog').showModal()}
const reviewLabels={place:'Handy-Ablageplatz',emergencyAction:'Vorbereitete Handlung',why:'Persönlicher Grund',review:'Vereinbarte Hürde'};
function openReview(){$('reviewTrigger').value=typeof plan.reflection?.trigger==='string'?plan.reflection.trigger:'';$('reviewHelped').value=typeof plan.reflection?.helped==='string'?plan.reflection.helped:'';$('reviewTarget').value='place';$('reviewRemember').checked=!!read(PLAN,true);$('reviewStatus').textContent='';renderReviewField();$('reviewDialog').showModal()}
function renderReviewField(){const target=$('reviewTarget').value;if(!reviewLabels[target])return;$('reviewNewField').innerHTML=target==='emergencyAction'?`<label>Meine neue vorbereitete Handlung<select id="reviewNewValue"><option value="">Bitte wählen</option>${Object.entries(actionLabels).map(([k,v])=>`<option value="${k}">${v}</option>`).join('')}</select></label>`:`<label>${target==='place'?'Neuer Ablageplatz':target==='why'?'Mein persönlicher Grund':'Meine konkrete Hürde'}<textarea id="reviewNewValue" rows="2" maxlength="${target==='place'?100:target==='why'?240:400}" placeholder="${target==='place'?'Zum Beispiel: in die Küche':target==='why'?'Wofür ich frei werden möchte …':'Zum Beispiel: Abends lade ich das Handy außerhalb des Schlafzimmers.'}"></textarea></label>`;$('reviewNewValue').oninput=previewReview;$('reviewNewValue').onchange=previewReview;previewReview()}
function reviewDraft(){const target=$('reviewTarget').value,raw=$('reviewNewValue')?.value.trim()||'';if(!reviewLabels[target])return null;if(target==='emergencyAction'&&raw&&!actionLabels[raw])return null;return {target,value:raw,trigger:$('reviewTrigger').value.trim(),helped:$('reviewHelped').value.trim()}}
function previewReview(){const d=reviewDraft();const changed=d&&!!d.value&&d.value!==plan[d.target];const reflectionChanged=d&&(d.trigger!==(plan.reflection?.trigger||'')||d.helped!==(plan.reflection?.helped||''));$('reviewApply').disabled=!(changed||reflectionChanged);$('reviewApply').textContent=changed?'Diese Planänderung übernehmen':'Rückblick übernehmen';if(!d)return;const old=plan[d.target]||'Noch nicht festgelegt',value=d.value;const display=v=>d.target==='emergencyAction'?(actionLabels[v]||v):v;$('reviewPreview').innerHTML=changed?`<strong>${reviewLabels[d.target]}</strong><dl class="change-preview"><dt>Bisher</dt><dd>${esc(display(old))}</dd><dt>Nach Übernahme</dt><dd>${esc(display(value))}</dd></dl>`:'<p>Dein Plan bleibt unverändert. Du kannst die beiden Rückblick-Antworten separat übernehmen.</p>'}
function applyReview(event){event.preventDefault();const d=reviewDraft();if(!d)return;const changed=!!d.value&&d.value!==plan[d.target];const reflectionChanged=d.trigger!==(plan.reflection?.trigger||'')||d.helped!==(plan.reflection?.helped||'');if(!changed&&!reflectionChanged)return;const updated={...plan,reflection:{trigger:d.trigger,helped:d.helped}};if(changed)updated[d.target]=d.value;if($('reviewRemember').checked){try{localStorage.setItem(PLAN,JSON.stringify(updated))}catch{storageOK=false;$('reviewStatus').textContent='Speichern ist nicht möglich. Deine Eingaben bleiben hier erhalten. Du kannst es erneut versuchen oder das Speicher-Häkchen abwählen.';return}}plan=updated;if(changed&&$('planDialog').open&&$(d.target))$(d.target).value=d.value;if($('reviewRemember').checked)$('remember').checked=true;render();previewReview();$('reviewStatus').textContent=$('reviewRemember').checked?'Übernommen und auf diesem Gerät gespeichert.':'Für diese geöffnete Seite übernommen. Ein zuvor gespeicherter Plan bleibt unverändert.'}
$('reviewOpen').onclick=openReview;
$('reviewTarget').onchange=renderReviewField;
$('reviewTrigger').oninput=previewReview;
$('reviewHelped').oninput=previewReview;
$('reviewForm').onsubmit=applyReview;
$('resetContentPrefs').onclick=()=>{if(!remove(PREFS,true)){$('prefsResetStatus').textContent='Zurücksetzen ist gerade nicht möglich.';return}contentPrefs={ratings:{},last:{}};s.content={};if(s.screen!=='done')save();render();$('prefsResetStatus').textContent='Deine Bewertungen wurden zurückgesetzt. Die nächste Pause beginnt ohne bevorzugte Inhalte.'};

if(migrated){save();remove(LEGACY)}
render();
